version: '3.8'

services:
  web:
    build: .
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb+srv://g7-dev:CgSFJMwbAWxFc79V@g7cluster01.uv8pzmk.mongodb.net/
    container_name: node-on-dockers